cookie:
  expiry_days: 30
  key: "626cd113fe30fce7"
  name: "admin_reauth"
credentials:
  usernames:
    dev:
      email: rodrigo.jamunda@itajunior.com.br
      failed_login_attempts: 0
      first_name: Rodrigo
      last_name: Jamundá Melo
      logged_in: False
      password: rodrigo.jamunda
      roles:
      - admin
      - editor
      - viewer
    dev_view:
      email: rodrigo.melo.9141@ga.ita.br
      failed_login_attempts: 0
      first_name: Rodrigo
      last_name: Jamundá Melo
      logged_in: False
      password: rodrigo.melo
      roles:
      - viewer
pre-authorized:
  emails:
